export const Project = [
  {
    icon: "🍂",
    name: "ac",
    description: "Animal Crossing music depending on the time and weather!",
    color: "bg-blue-500",
    dark_color: "bg-blue-600",
    text: "text-white",
    dark_text: "text-white",
    default: "https://ac.vercel.app",
    image: "https://cdn.dont-ping.me/ac.png",
  },
  {
    icon: "📚",
    name: "sb-next-ts-tailwind",
    description:
      "A template for Storybook + Next.js + Typescript + Tailwindcss!",
    color: "bg-red-400",
    dark_color: "bg-red-500",
    text: "text-white",
    dark_text: "text-white",
    default: "https://sb-next-ts-tailwind.vercel.app/",
    image: "https://cdn.dont-ping.me/sb.png",
  },
  {
    icon: "🌙",
    name: "presence",
    description: "A simple and elegant solution to images for socials media!",
    color: "bg-yellow-200",
    dark_color: "bg-yellow-400",
    text: "text-black",
    dark_text: "text-white",
    default: "https://presence.im",
    image: "https://cdn.dont-ping.me/presence.png",
  },
  {
    icon: "☁️",
    name: "cdn",
    description: "A public file host. + an endpoint :)",
    color: "bg-gray-300",
    dark_color: "bg-gray-300",
    text: "text-black",
    dark_text: "text-black",
    default: "https://cdn.dont-ping.me",
    image: "https://cdn.dont-ping.me/cdn.png",
  },
  {
    icon: "⌘",
    name: "cmd + f",
    description: "⌘ + F, find a new way to shorten urls.",
    color: "bg-[#f1f2f6]",
    dark_color: "bg-[#e0e2eb]",
    text: "text-black",
    dark_text: "text_black",
    default: "https://cmdf.at",
    image: "https://cdn.dont-ping.me/cmdf.png",
  },
  {
    icon: "🎵",
    name: "use-listen-along",
    description: "Typescript React Hook for listening along on spotify.",
    color: "bg-indigo-500",
    dark_color: "bg-indigo-600",
    text: "text-white",
    dark_text: "text-white",
    default: "https://npmjs.org/use-listen-along",
    image: "https://cdn.dont-ping.me/listen-along.png",
  },
  {
    icon: "🔎",
    name: "new → tab",
    description: "An uber-customizable new tab experience.",
    color: "bg-gray-800",
    dark_color: "bg-gray-900",
    text: "text-white",
    dark_text: "text-white",
    default: "https://newtab.vc/",
    image: "https://cdn.dont-ping.me/tab.png",
  },
];
