/**
 * @type {Array.<{
 *  icon: string,
 *  name: string,
 *  id: string,
 *  type: "Project" | "Research paper",
 *  description: string,
 *  author: { name: string, image: string },
 *  date: Date,
 *  color?: string,
 *  dark_color?: string,
 *  text?: string,
 *  dark_text?: string,
 *  default: string,
 *  image: string
 * }>}
 */
export const Project = [
  {
    icon: "🍂",
    name: "ac",
    id: "ac",
    type: "Project",
    description: "Animal Crossing music depending on the time and weather!",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("December 17 2020"),
    color: "bg-blue-500",
    border: "border-blue-500",
    dark_color: "bg-blue-600",
    text: "text-white",
    dark_text: "dark:text-white",
    default: "https://ac.vercel.app",
    image: "https://cdn.dont-ping.me/ac.png",
  },
  {
    icon: "📚",
    name: "sb-next-ts-tailwind",
    id: "s-n-t-t",
    type: "Project",
    description:
      "A template for Storybook + Next.js + Typescript + Tailwindcss!",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("June 2 2021"),
    color: "bg-red-400",
    border: "border-red-400",
    dark_color: "dark:bg-red-500",
    text: "text-white",
    dark_text: "dark:text-white",
    default: "https://sb-next-ts-tailwind.vercel.app/",
    image: "https://cdn.dont-ping.me/sb.png",
  },
  {
    icon: "🌙",
    name: "presence",
    id: "presence",
    type: "Project",
    description: "A simple and elegant solution to images for socials media!",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("August 1 2021"),
    color: "bg-yellow-200",
    border: "border-yellow-200",
    dark_color: "dark:bg-yellow-400",
    text: "text-black",
    dark_text: "dark:text-white",
    default: "https://presence.im",
    image: "https://cdn.dont-ping.me/presence.png",
  },
  {
    icon: "☁️",
    name: "cdn",
    id: "cdn",
    type: "Project",
    description: "A public file host. + an endpoint :)",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("August 14 2021"),
    color: "bg-gray-300",
    border: "border-gray-300",
    dark_color: "dark:bg-gray-300",
    text: "text-black",
    dark_text: "dark:text-black",
    default: "https://cdn.dont-ping.me",
    image: "https://cdn.dont-ping.me/cdn.png",
  },
  {
    icon: "⌘",
    name: "cmd + f",
    id: "cmdf",
    type: "Project",
    description: "⌘ + F, find a new way to shorten urls.",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("August 14 2021"),
    color: "bg-[#f1f2f6]",
    border: "border-[#f1f2f6]",
    dark_color: "dark:bg-[#e0e2eb]",
    text: "text-black",
    dark_text: "dark:text_black",
    default: "https://cmdf.at",
    image: "https://cdn.dont-ping.me/cmdf.png",
  },
  {
    icon: "🎵",
    name: "use-listen-along",
    id: "listen-along",
    type: "Project",
    description: "Typescript React Hook for listening along on spotify.",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("August 20 2021"),
    color: "bg-indigo-500",
    border: "border-indigo-500",
    dark_color: "dark:bg-indigo-600",
    text: "text-white",
    dark_text: "dark:text-white",
    default: "https://npmjs.org/use-listen-along",
    image: "https://cdn.dont-ping.me/listen-along.png",
  },
  {
    icon: "🔎",
    name: "new → tab",
    id: "newtab",
    type: "Project",
    description: "An uber-customizable new tab experience.",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("September 16 2021"),
    color: "bg-gray-800",
    border: "border-gray-800",
    dark_color: "dark:bg-gray-900",
    text: "text-white",
    dark_text: "dark:text-white",
    default: "https://newtabs.vercel.app/",
    image: "https://cdn.dont-ping.me/tab.png",
  },
  {
    icon: "💬",
    name: "canary",
    id: "canary",
    type: "Project",
    description: "A small, compact & modern UI kit.",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("November 1 2021"),
    color: "bg-green-500",
    border: "border-green-500",
    dark_color: "dark:bg-green-600",
    text: "text-white",
    dark_text: "dark:text-white",
    default: "https://npmjs.org/@canary-ui/react",
    image: "https://cdn.dont-ping.me/canary.png",
  },
  {
    icon: "📸",
    name: "mμ",
    id: "mu",
    type: "Project",
    description: "Easy open graph generation.",
    author: {
      name: "Matt",
      image: "https://github.com/punctuations.png",
    },
    date: new Date("Oct 11 2022"),
    color: "bg-gradient-to-r from-purple-500 to-pink-500",
    border: "border-white/50",
    dark_color: "dark:from-pink-500 dark:to-purple-500",
    text: "text-white",
    dark_text: "dark:text-white",
    default: "https://mu.canary.mx",
    image: "https://cdn.dont-ping.me/mu.png",
  },
];
